name: Nilayah Peter
theme: jekyll-theme-slate

title: Nilayah Peter
description: **Purdue University** || Bachelor of Science || May 2025

I am a Computer Engineer with a concentration in Software Engineering with a minor in Art and Design Studio. I am looking for a summer 2024 internship to excel and grow my skills of programming.

Below are projects I have personally worked on in my free time.

#Magic Eight Ball

This project is similar to a magic eight ball... blah blah

```
ADD LINK
```
